name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "dev/**"
      - "alpha/**"
      - "release/**"

permissions:
  contents: read
  issues: write

jobs:
  publication:
    uses: kungfu-systems/buildchain/.github/workflows/publication-artifact.yml@72add9cc62566c1c1cbf3b1f01d2d4d2f74a2826
    with:
      buildchain-ref: 72add9cc62566c1c1cbf3b1f01d2d4d2f74a2826
      buildchain-contract-lock-path: .buildchain/contract-lock.json
      toolchain-type: config
      verify-command: make check
      artifact-name: "paper-observer-declared-timelines"
