name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "dev/**"
      - "alpha/**"
      - "release/**"

permissions:
  contents: read
  issues: write

jobs:
  publication:
    uses: kungfu-systems/buildchain/.github/workflows/publication-artifact.yml@acddf9d7047a40de692ae4463aa84039283e5bc0
    with:
      buildchain-ref: acddf9d7047a40de692ae4463aa84039283e5bc0
      buildchain-contract-lock-path: .buildchain/contract-lock.json
      toolchain-type: config
      verify-command: make check
      artifact-name: "paper-observer-declared-timelines"
