name: Verify

on:
  pull_request:
  push:
    branches:
      - "dev/v*/v*"
      - "alpha/v*/v*"
      - "release/v*/v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: kungfu-systems/buildchain/.github/workflows/check.yml@105aedb246d98d66483c64bf06bada0523143353
    with:
      buildchain-ref: 105aedb246d98d66483c64bf06bada0523143353
      require-version-state: true
      upload-artifacts: true
