name: Verify

on:
  pull_request:
  push:
    branches:
      - "dev/v*/v*"
      - "alpha/v*/v*"
      - "release/v*/v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: kungfu-systems/buildchain/.github/workflows/check.yml@ecd6e8e0312fa77ecc5e05554944b162fb144718
    with:
      buildchain-ref: ecd6e8e0312fa77ecc5e05554944b162fb144718
      require-version-state: true
      upload-artifacts: true
