name: Verify

on:
  pull_request:
  push:
    branches:
      - "dev/v*/v*"
      - "alpha/v*/v*"
      - "release/v*/v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: kungfu-systems/buildchain/.github/workflows/check.yml@acddf9d7047a40de692ae4463aa84039283e5bc0
    with:
      require-version-state: true
      upload-artifacts: true
